[tool.black]
#skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
  /(
     \.git
   | \.venv
  )/
  # don't rewrite generated files
  | python-client/openrtist/src/design.py
  | python-client/openrtist/src/openrtist_pb2.py
  | server/openrtist_pb2.py
)
'''

[tool.isort]
profile = "black"
